version: '3.8'

volumes:
    dynamodb-local:
        driver: local

services:
    dynamodb:
        build: ./database
        image: amazon/dynamodb-local:latest
        volumes:
            - dynamodb-local:/home/dynamodblocal/db
        ports:
            - "8000:8000"

    "translation-api":
        build: "./application"
        ports:
        - 5000:5000
        volumes:
        - ./application:/app
        depends_on: 
            - dynamodb
        environment:
            AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
            AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'